# Generated by Django 3.1.7 on 2021-05-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='realtime',
            table='real_time2',
        ),
    ]
