# Generated by Django 3.1.7 on 2021-05-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_auto_20210509_1312'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='realtime',
            table='real_time',
        ),
    ]
