# Generated by Django 3.1.7 on 2021-05-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_auto_20210509_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thresholds',
        ),
    ]
